apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    redis-node: "true"
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas.slave }}
  template:
    metadata:
      labels:
        name: redis
{{ include "labels.standard" . | indent 8 }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis_image }}"
        resources:
{{ toYaml .Values.resources.slave | indent 10 }}
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
          {{- if .Values.ceph.enabled }}
          subPath: {{ .Values.ceph.masterStorageId }}
          {{- end }}
      volumes:
      - name: data
      {{- if .Values.ceph.enabled }}
        flexVolume:
          driver: rook.io/rook
          fsType: ceph
          options:
            fsName: data
            clusterName: rook
      {{- else }}
        {{- if .Values.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistentVolume.existingClaim }}{{ .Values.persistentVolume.existingClaim }}{{- else }}{{ template "name" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
      {{- end -}}
